### ISSUE TITLE
[Question] Project status

### ISSUE THREAD

**Issue by AubSs** [FallingCeilingS/vue-virtualised#16]
Hello!
Thank you for trying to solve virtualized element problem on vue 3!

Do you think your lib can be used on production environments ?
If not, do you have any ETA in mind ?
Your lib seems promising !

Thank you

**Comment by FallingCeilingS** [comment]
@AubSs - thank you for being interested in my project. I'm happy this library helps people resolve their problems.

I think this library can be used in production environments for sure!
Also, as it's an ongoing project, it will roll out new versions as well as documents/demos for the time being.
Please refer to the [milestone page](https://github.com/FallingCeilingS/vue-virtualised/milestones) for more details of what I plan to do and ETAs.

Feel free to raise any issues.

Regards,
Junxiang
